### ISSUE TITLE
Where does the teapot data come from?

### ISSUE THREAD

**Issue by panovr** [andystanton/raytracer-rs#1]
Hi,
  thanks for this wonderful rust raytracer.
  I note that you have added a teapot model for raytracing, and this is great.
  So I just wonder where are the teapot data (I mean VERTICES/NORMALS/INDICES) come from?
  Thanks!

**Comment by andystanton** [comment]
hi @panovr 

Thank you! The teapot is the famous [Utah Teapot](https://en.wikipedia.org/wiki/Utah_teapot) which is often referenced in graphics programs.

I converted a [Wavefront OBJ](https://en.wikipedia.org/wiki/Wavefront_.obj_file) version of the teapot model and put it in my source code so I didn't have to load it at runtime. The VERTICES/NORMALS/INDICES are the same as the `v/vn/f` parts of OBJ files.

I can't remember where I found the original model, and there are many versions of it online, but here are two ways you can find one:
1. The Wikipedia [Utah Teapot article](https://en.wikipedia.org/wiki/Utah_teapot#OBJ_conversion) links to [newell_teaset.zip](https://users.cs.utah.edu/~natevm/newell_teaset/newell_teaset.zip) which includes the teapot model in Wavefront OBJ format.
2. The free [Blender](https://www.blender.org) 3D Modelling software includes an addon called [Mesh Extra Objects](https://docs.blender.org/manual/en/latest/addons/add_mesh/mesh_extra_objects.html) that contains the teapot model. You could export the model to whatever format you want from here.

**Comment by panovr** [comment]
@andystanton thanks for the teapot model info!
As I understanding, for raytracing the teapot model, we need to test ray-triangle intersection, because the teapot model is constructed by triangles mesh.
May you interpret the algorithm a bit more about this code: [https://github.com/andystanton/raytracer-rs/blob/e000aeba06479636275df18899859b803097b4c9/src/triangle.rs#L33](https://github.com/andystanton/raytracer-rs/blob/e000aeba06479636275df18899859b803097b4c9/src/triangle.rs#L33)

**Comment by andystanton** [comment]
Hi @panovr, this code is the Möller-Trumbore ray/triangle intersection algorithm. There is a better explanation than I can provide on the [Wikipedia page about the algorithm](https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm) that explains the steps involved.

**Comment by panovr** [comment]
@andystanton I did a quick test with my C# raytracer based on your code and model data.
![render](https://github.com/andystanton/raytracer-rs/assets/319796/db744607-8f9a-4a4a-ae2c-caf90586f59f)


The render result still has some problems.

I tried with metal material. It seems that the teapot lid rendering has some prolems.
![render](https://github.com/andystanton/raytracer-rs/assets/319796/34aa122a-f7f7-442a-af25-8a61d13e6cd4)

**Comment by panovr** [comment]
The wrong rendering result is because there was a bug in my teapot hit implementing code. After fixing the bug, I can get the right rendering result.

![render](https://github.com/andystanton/raytracer-rs/assets/319796/dddf2891-19a9-41d8-a017-1d3bf7fa15d8)
